version: "3.8"
services: 
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      - SERVER_URL=${SERVER_URL}
      - CLIENT_PORT=${CLIENT_PORT}
    stdin_open: true
    tty: true